### PR TITLE
Portfolio page and bug fixes

### LINKED ISSUE #84: Add Portfolio functionality
- [ ] portfolio value, synths minted, potential rewards, success tokens
- [ ] fetch user synths add it in rows

### LINKED ISSUE #125: Website can only be seen with a wallet installed
If a user tries to access the website without a wallet (e.g. metamask) installed the website will no load.
Switch provider.

### LINKED ISSUE #145: Format numbers on homepage

### LINKED ISSUE #147: Connect dropdown to lang switcher

### PR DESCRIPTION
**Pull request by ghost**
- Fixes private _network bug (previously prevented to get the right network id in the sdk)
- Formats numbers on homepage
- Fixes signer bug
- Adds data to portfolio site

### CODE REVIEW

File: src/components/layout/Header.vue [hunk 1]
```diff
@@ -239,8 +254,8 @@ export default {
                 v-if="!isLangDropDownOpen"
                 v-click-away="closePopup"
             >
-                <li class="min-w-max cursor-pointer p-1">
-                    <span>Spanish</span>
+                <li v-for="locale in $i18n.global.availableLocales" :key="locale" @click="switchLocale(locale)" class="min-w-max cursor-pointer p-1">
+                    <span>{{ locale }}</span>
```
Comment (ethedev) [inline src/components/layout/Header.vue]: when you select a language, it will only appear after clicking outside of the dropdown, it should appear selected directly when clicking on it

File: src/views/Portfolio.vue [hunk 2]
```diff
@@ -169,92 +188,64 @@
...
-        minted_qty: 120,
-        lp_qty: 120,
-        price: 120,
-        collateral: "ETH",
-        status: 1,
-    },
-]
-
+import { computed, ref } from "vue"
+import { useSynthsSDK } from "../composables/useSynthsSDK"
```
Comment (ethedev) [inline src/views/Portfolio.vue]:
```suggestion
import { useSynthsSDK } from "@/composables/useSynthsSDK"
```

File: src/views/Portfolio.vue [hunk 3]
```diff
@@ -169,92 +188,64 @@
...
+                    <td><div class="animate-pulse bg-white">.</div></td>
+                    <td>
+                        <div class="animate-pulse bg-white">
+                            <span class="text-white">.</span>
+                        </div>
+                    </td>
+                    <td>
+                        <div class="rounded-full animate-pulse bg-white w-6 h-6" />
+                    </td>
+                </tr>
```
Comment (ethedev) [inline src/views/Portfolio.vue]: to convert it into a component, then use it up and here

File: src/views/Portfolio.vue [hunk 4]
```diff
@@ -117,9 +117,27 @@
...
+                    <td><div class="animate-pulse bg-white">.</div></td>
+                    <td>
+                        <div class="animate-pulse bg-white">
+                            <span class="text-white">.</span>
+                        </div>
+                    </td>
+                    <td class="pr-2 m-0">
+                        <div class="rounded-full animate-pulse bg-white w-6 h-6" />
+                    </td>
+                </tr>
```
Comment (ethedev) [inline src/views/Portfolio.vue]: this looks nice but its too close to eachother, adding some extra space after the first item and making sure all spaces are equal will make it look better

File: src/components/layout/Header.vue (hunk 1 above)
Comment (ghost) [reply src/components/layout/Header.vue]: Has something to do with the dropdown not closing.

File: src/views/Portfolio.vue (hunk 3 above)
Comment (ghost) [reply src/views/Portfolio.vue]: This would mean we would add both loaders (for mobile and desktop) in separate components.

Comment (ethedev) [reply src/views/Portfolio.vue]: both should be in the same component, on the mobile it would just show what it supposed to

File: src/composables/useSynthsSDK.ts [hunk 5]
```diff
@@ -1,28 +1,47 @@
...
-        const networkId: number = (await provider.getNetwork()).chainId
-        synthsSDK.value = await Synths.create({ ethersProvider: provider })
-        totalMarketData.value = await getTotalMarketData([networkId], defaultAssetsConfig)
-        recentSynthData.value = await getRecentSynthData(networkId, defaultAssetsConfig)
-        lspPortfolio.value = await synthsSDK.value.getLSPPortfolio(provider.getSigner())
+        const POLYSCAN_API_KEY = import.meta.env.VITE_POLYSCAN_API_KEY as string
+
+        synthsSDK = await Synths.create({ ethersProvider: provider, userAssetsConfig: defaultTestAssetsConfig })
+        totalMarketData.value = await getTotalMarketData([networkId], synthsSDK.config, POLYSCAN_API_KEY)
+        recentSynthData.value = await getRecentSynthData(networkId, synthsSDK.config, POLYSCAN_API_KEY)
```
Comment (ethedev) [inline src/composables/useSynthsSDK.ts:29]: should be separate and selectable depending on the network we are on

File: src/components/layout/Header.vue [hunk 6]
```diff
@@ -185,15 +200,15 @@ export default {
                     class="hidden lg:flex px-2 py-1.5 font-semibold text-purpleLight text-sm cursor-pointer"
                     @click="(isLangDropDownOpen = !isLangDropDownOpen);(isHelpDropDownOpen=false);(isWalletDropDownOpen=false)"
                 >
-                    English
+                    {{ getLanguageById($i18n.global.locale) }}
```
Comment (ethedev) [inline src/components/layout/Header.vue]: that is showing "en" on page load, it should show "English"

**Review by ethedev — CHANGES_REQUESTED** [review]

File: src/composables/useSynthsSDK.ts (hunk 5 above)
Comment (ghost) [reply src/composables/useSynthsSDK.ts:29]: Not sure what you mean by that. It passes the network that is connected.

Comment (ethedev) [reply src/composables/useSynthsSDK.ts:29]: `POLYSCAN_API_KEY`

Comment (ghost) [reply src/composables/useSynthsSDK.ts:29]: We only need the key for polyscan and as this is an optional param on the helpers and it will just be ignored if it is on mainnet i think we can keep it as is instead of adding a switch or if / else statement.

Comment (ethedev) [reply src/composables/useSynthsSDK.ts:29]: for now thats ok since we will have everything on polygon, but for a later update just pass it with the `synthsSDK.config` values

**Review by ethedev — APPROVED** [review]
